CRM/Controllers/CRMController.cs
using CRM.Data;
using CRM.Data.Repository;
using CRM.Models;
using CRM.Models.Raw;
using CRM.Models.VM;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRM.Controllers
{
    public class CRMController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CRMController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(CRMDATA CRMDATA, CRMDATAChild CRMDATAChild)
        {
            //CRMDATA.City = "Multan";
            CRMDATA.Country = "Pakistan";
            var Con = new Repo<Contacts>().GetAllData("SELECT Mob as Contact FROM CRMDATA");
            var VM = new CRMVM
            {
                CRMDATA = CRMDATA,
                CRMDATAChild = CRMDATAChild,
                Contacts= Con.ToList(),
            };
            return View(VM);
        }
        
        [HttpPost,ActionName("Index")]
        public IActionResult Save(CRMDATA CRMDATA ,CRMDATAChild CRMDATAChild)
        {
            CRMDATA.Userid = HttpContext.Session.GetString("Userid");
            CRMDATAChild.Userid = HttpContext.Session.GetString("Userid");
            CRMDATAChild.DateTime = DateTime.Now;
            CRMDATAChild.Mob = CRMDATA.Mob;
            var Count = new Repo<string>().GetMaxId("SELECT COUNT(*) AS Expr1 FROM CRMDATA WHERE (Mob = '"+ CRMDATA.Mob + "')");
            if (Count == 0)
            {
                _context.CRMDATA.Add(CRMDATA);
                _context.CRMDATAChild.Add(CRMDATAChild);
            }
            else
            {
                _context.CRMDATAChild.Add(CRMDATAChild);
                var db = _context.CRMDATA.SingleOrDefault(c=>c.Mob == CRMDATA.Mob);
                db.Mob = CRMDATA.Mob;
                db.CusName = CRMDATA.CusName;
                db.City = CRMDATA.City;
                db.Country = CRMDATA.Country;
                db.Address = CRMDATA.Address;
                db.Email = CRMDATA.Email;
                db.WebUrl = CRMDATA.WebUrl;
            }
            
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Action(string id)
        {
            var Mobs = _context.CRMDATA.FromSqlRaw("SELECT * FROM CRMDATA WHERE (Mob = '" + id + "')").ToList();
            return Json(Mobs);
        }
        public IActionResult GetCRMList(string id)
        {
            var List = new Repo<CRMVMQ>().GetAllData("SELECT CRMDATAChild.id, CRMDATAChild.Userid, CRMDATAChild.Mob, CRMDATAChild.Remarks, CRMDATAChild.DateTime, [User].Name AS UserName FROM CRMDATAChild INNER JOIN [User] ON CRMDATAChild.Userid = [User].id WHERE(CRMDATAChild.Mob = '"+ id +"') AND (Userid = '" + HttpContext.Session.GetString("Userid") + "')").ToList();
            return Json(List);
        }
    }
}

CRM/Views/CRM/Index.cshtml
@model CRM.Models.VM.CRMVM
@{
    ViewData["Title"] = "Index";
}
<section class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        @*<div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">CRM</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="#!">CRM</a></li>
                                <li class="breadcrumb-item"><a href="#!">CRM Form/Table</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>*@
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <div class="row">
            <!-- [ form-element ] start -->
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="mt-5">CRM Form</h5>
                        <hr>
                        <form asp-action="Index" method="post">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="inputState">Mobile Contact/No</label>
                                    <input id="tags" class="form-control" required asp-for="CRMDATA.Mob"  onkeyup="Action(this.value)" onchange="Action(this.value)">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inputEmail4">Customer Name</label>
                                    <input type="text" asp-for="CRMDATA.CusName" required id="Cus" class="form-control" placeholder="Name">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">City</label>
                                    <input type="text" asp-for="CRMDATA.City" id="City" class="form-control" placeholder="City">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">Country</label>
                                    <input type="text" asp-for="CRMDATA.Country" id="Country" class="form-control" placeholder="Country">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label>Address</label>
                                    <input type="text" asp-for="CRMDATA.Address" id="Address" class="form-control" placeholder="Address">
                                </div>
                                <div class="form-group col-md-4">
                                    <label>Email Address</label>
                                    <input type="text" asp-for="CRMDATA.Email" id="Email" class="form-control" placeholder="Email Address">
                                </div>
                                <div class="form-group col-md-4">
                                    <label>Web Url</label>
                                    <input type="text" asp-for="CRMDATA.WebUrl" id="Url" class="form-control" placeholder="http://">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-12">
                                    <label>Remarks</label>
                                    <textarea class="form-control" asp-for="CRMDATAChild.Remarks" cols="5" rows="3"></textarea>
                                </div>
                            </div>
                            <br />
                            <div class="form-row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn  btn-primary"><i class="feather icon-plus"></i> Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- [ form-element ] end -->
            <!--Table Start-->
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-header">
                        <h5>History</h5>
                    </div>
                    <center>
                        <label id="lblmodAlertClient" style="color:red;"></label>
                    </center>
                    <div class="card-body">
                        <div class="dt-responsive table-responsive">
                            <table id="tblClients" class="table table-striped table-bordered nowrap">
                                <thead>
                                    <tr>
                                        <th>User Name</th>
                                        <th>Date Time</th>
                                        <th>ConTent</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--Table End-->
        </div>
        <!-- [ Main Content ] end -->

    </div>
</section>

<!-- Modal -->
<div class="modal hide fade" id="orderModal" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div id="Indata" class="modal-body"></div>
            @*<div id="orderItems" class="modal-body"></div>*@
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
<script>
    $(function () {
        var availableTags = [
            @foreach (var Lst in Model.Contacts)
            {
                <text>"@Lst.Contact",</text>
            }
        ];
        $("#tags").autocomplete({
            minLength: 3,
            source: availableTags
        });
    });
    function Action(id) {
        var count = document.getElementById("tags").value.length;
        if (count == 0) {
            $("#Cus").val('');
            $("#City").val('');
            $("#Country").val('');
            $('#Url').val('');
            $('#Address').val('');
            $('#Email').val('');
            $('#Remarks').val('');
            $("#tblClients tbody tr").remove();
        }
        let Indata = ``;
//        alert(Indata);
        $.ajax({
            url: '@Url.Action("Action", "CRM")',
            type: "POST",
            data: { "id": id },
        "success": function (data) {
        if (data != null) {
            var vdata = data;
            $("#Cus").val(vdata[0].cusName);
            $("#City").val(vdata[0].city);
            $("#Country").val(vdata[0].country);
            $('#Url').val(vdata[0].webUrl);
            $('#Address').val(vdata[0].address);
            $('#Email').val(vdata[0].email);
            $('#Remarks').val(vdata[0].remarks);
            }

    }
        });
          $.ajax({
              url: '@Url.Action("GetCRMList", "CRM")',
              type: "GET",
              contentType: "application/json; charset=utf-8",
              data: { 'id': id },
              dataType: "json",
              success: function (data1) {
                  document.getElementById("lblmodAlertClient").innerHTML = data1.length + " records found";
                  if (data1 != null) {
                      $.each(data1, function (i, item) {
                          var row = "";
                          row += "<tr ><td>" + item.userName
                              //+ "</td><td>" + item.dateTime
                              + "</td><td>" + moment(item.dateTime).format('DD-MM-YYYY h:mm A')
                              + "</td><td data-toggle='modal' data-target='#orderModal'><input onclick='removeCandidate(this.value)' readonly class='form-control' value='" + item.remarks +"' />"
                              + "</td></tr>";
                          $('#tblClients tbody').append(row);
                          
                      });

                      //document.getElementById('remove-candidates-modal-body').innerHTML = item.remarks;
                  };
              },
              error: function (result) {
                  alert("Error");
              }
          });
          if ($("#tags").val().length > 1) {
              $("#Cus").val('');
              $("#City").val('');
              $("#Country").val('');
              $('#Url').val('');
              $('#Address').val('');
              $('#Email').val('');
              //$('#Remarks').val('');
              $("#tblClients tbody tr").remove();
          }
    };
    function removeCandidate(id) {

        var Newdata = id;
        document.getElementById('Indata').innerHTML = Newdata;
        //alert(Newdata);
    }
    $(function () {
        $('#orderModal').modal({
            keyboard: true,
            backdrop: "static",
            show: false,
           
        }).on('show', function () { //subscribe to show method
            var getIdFromRow = $(event.target).closest('tr').data('id'); //get the id from tr
            //make your ajax call populate items or what even you need
            $(this).find('#orderDetails').html($('<b> Order Id selected: ' + getIdFromRow + '</b>'))
        });
    });
    //$(function () {
    //    var availableTags = [
    //        "ActionScript",
    //        "AppleScript",
    //        "Asp",
    //        "BASIC",
    //        "C",
    //        "C++",
    //        "Clojure",
    //        "COBOL",
    //        "ColdFusion",
    //        "Erlang",
    //        "Fortran",
    //        "Groovy",
    //        "Haskell",
    //        "Java",
    //        "JavaScript",
    //        "Lisp",
    //        "Perl",
    //        "PHP",
    //        "Python",
    //        "Ruby",
    //        "Scala",
    //        "Scheme"
    //    ];
    //    $("#tags").autocomplete({
    //        minLength: 2,
    //        source: availableTags
    //    });
    //});

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.js"></script>